export const LOADING_DATA_SUCCESS = 'LOADING_DATA_SUCCESS'
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY'

export const OPEN_MODAL_CREATE_PROPERTY = 'OPEN_MODAL_CREATE_PROPERTY'
export const CLOSE_MODAL_CREATE_PROPERTY = 'CLOSE_MODAL_CREATE_PROPERTY'

export const CLOSE_MODAL_FILTER = 'CLOSE_MODAL_FILTER'
export const OPEN_MODAL_FILTER = 'OPEN_MODAL_FILTER'

export const OPEN_MAP = 'OPEN_MAP'
export const CLOSE_MAP = 'CLOSE_MAP'

export const FILTER_CHANGED = 'FILTER_CHANGED'
export const SET_FILTERED_PROPERTIES = 'SET_FILTERED_PROPERTIES'
export const CLEAR_FILTER_ACTION = 'CLEAR_FILTER_ACTION'

export const SET_ACTIVE_CARD = 'SET_ACTIVE_CARD'
export const SET_ACTIVE_INFO_WINDOW = 'SET_ACTIVE_INFO_WINDOW'
export const DELETE_ACTIVE_INFO_WINDOW = 'DELETE_ACTIVE_INFO_WINDOW'